// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var StackNavigation = require("./StackNavigation.bs.js");

var app = StackNavigation.make;

exports.app = app;
/* StackNavigation Not a pure module */
