// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Expo = require("expo");
var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Platform$BsReactNative = require("bs-react-native/src/platform.js");

var match = Platform$BsReactNative.os(/* () */0) === /* Android */0;

var pageContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#FF6600"])),
        /* :: */[
          Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [match ? Expo.Constants.statusBarHeight : 0.0])),
          /* [] */0
        ]
      ]
    ]);

var news = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F6F6EF"])),
        /* [] */0
      ]
    ]);

var separator = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.height(/* Pt */Block.__(0, [1.0])),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#ededed"])),
        /* :: */[
          Style$BsReactNative.marginTop(/* Pt */Block.__(0, [5.0])),
          /* :: */[
            Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [5.0])),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.pageContainer = pageContainer;
exports.news = news;
exports.separator = separator;
/* pageContainer Not a pure module */
