// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Expo = require("expo");
var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Platform$BsReactNative = require("bs-react-native/src/platform.js");

var activityIndicator = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F6F6EF"])),
      /* [] */0
    ]);

var match = Platform$BsReactNative.os(/* () */0) === /* Android */0;

var pageContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#FF6600"])),
        /* :: */[
          Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [match ? Expo.Constants.statusBarHeight : 0.0])),
          /* [] */0
        ]
      ]
    ]);

var news = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F6F6EF"])),
        /* [] */0
      ]
    ]);

var separator = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.height(/* Pt */Block.__(0, [1.0])),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#ededed"])),
        /* :: */[
          Style$BsReactNative.marginTop(/* Pt */Block.__(0, [5.0])),
          /* :: */[
            Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [5.0])),
            /* [] */0
          ]
        ]
      ]
    ]);

var listItemContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        Style$BsReactNative.flexWrap(/* Nowrap */1),
        /* :: */[
          Style$BsReactNative.flexDirection(/* Row */0),
          /* [] */0
        ]
      ]
    ]);

var listIndex = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.1),
      /* :: */[
        Style$BsReactNative.alignSelf(/* Center */2),
        /* [] */0
      ]
    ]);

var listContent = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.8),
      /* :: */[
        Style$BsReactNative.paddingLeft(/* Pt */Block.__(0, [5.0])),
        /* :: */[
          Style$BsReactNative.paddingRight(/* Pt */Block.__(0, [5.0])),
          /* [] */0
        ]
      ]
    ]);

var title = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [5.0])),
      /* :: */[
        Style$BsReactNative.fontWeight(/* Bold */737455525),
        /* [] */0
      ]
    ]);

var domain = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontStyle(/* Italic */1),
      /* :: */[
        Style$BsReactNative.color(/* String */Block.__(0, ["#727270"])),
        /* [] */0
      ]
    ]);

var timeAgoAndUser = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, ["#727270"])),
      /* [] */0
    ]);

var listCommentAndFunc = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.1),
      /* :: */[
        Style$BsReactNative.alignSelf(/* Center */2),
        /* [] */0
      ]
    ]);

exports.activityIndicator = activityIndicator;
exports.pageContainer = pageContainer;
exports.news = news;
exports.separator = separator;
exports.listItemContainer = listItemContainer;
exports.listIndex = listIndex;
exports.listContent = listContent;
exports.title = title;
exports.domain = domain;
exports.timeAgoAndUser = timeAgoAndUser;
exports.listCommentAndFunc = listCommentAndFunc;
/* activityIndicator Not a pure module */
