// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var floatingActionButton = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F7F5F8"])),
      /* :: */[
        Style$BsReactNative.borderStyle(/* Solid */0),
        /* :: */[
          Style$BsReactNative.borderColor(/* String */Block.__(0, ["black"])),
          /* :: */[
            Style$BsReactNative.width(/* Pt */Block.__(0, [40.0])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [40.0])),
              /* :: */[
                Style$BsReactNative.borderRadius(100.0),
                /* :: */[
                  Style$BsReactNative.position(/* Absolute */0),
                  /* :: */[
                    Style$BsReactNative.bottom(/* Pt */Block.__(0, [5.0])),
                    /* :: */[
                      Style$BsReactNative.right(/* Pt */Block.__(0, [20.0])),
                      /* :: */[
                        Style$BsReactNative.alignItems(/* Center */2),
                        /* :: */[
                          Style$BsReactNative.justifyContent(/* Center */2),
                          /* :: */[
                            Style$BsReactNative.elevation(2.0),
                            /* :: */[
                              Style$BsReactNative.shadowColor(/* String */Block.__(0, ["#000000"])),
                              /* :: */[
                                Style$BsReactNative.shadowOpacity(0.4),
                                /* :: */[
                                  Style$BsReactNative.shadowRadius(1.0),
                                  /* :: */[
                                    Style$BsReactNative.shadowOffset(1.0, 0.0),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var RefreshButton = /* module */[/* floatingActionButton */floatingActionButton];

var hackerNewsHeaderBackgroundColor = Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#FF6600"]));

var hackerNewsContentBackgroundColor = Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F6F6EF"]));

var grayColor = Style$BsReactNative.color(/* String */Block.__(0, ["#727270"]));

var activityIndicator = Style$BsReactNative.style(/* :: */[
      hackerNewsContentBackgroundColor,
      /* [] */0
    ]);

var pageContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        hackerNewsHeaderBackgroundColor,
        /* :: */[
          Style$BsReactNative.overflow(/* Hidden */1),
          /* [] */0
        ]
      ]
    ]);

var grayFontColor = Style$BsReactNative.style(/* :: */[
      grayColor,
      /* [] */0
    ]);

var textCenter = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.textAlign(/* Center */3),
      /* [] */0
    ]);

var header = Style$BsReactNative.style(/* :: */[
      hackerNewsHeaderBackgroundColor,
      /* [] */0
    ]);

var imageHW = /* Pt */Block.__(0, [17.5]);

var imageSize_000 = Style$BsReactNative.width(imageHW);

var imageSize_001 = /* :: */[
  Style$BsReactNative.height(imageHW),
  /* [] */0
];

var imageSize = /* :: */[
  imageSize_000,
  imageSize_001
];

var image = Style$BsReactNative.style(imageSize);

var Common_003 = /* navigationTint : String */["black"];

var Common = /* module */[
  /* grayFontColor */grayFontColor,
  /* textCenter */textCenter,
  /* header */header,
  Common_003,
  /* imageHW */imageHW,
  /* imageSize */imageSize,
  /* image */image
];

var newsContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(1.0),
      /* :: */[
        hackerNewsContentBackgroundColor,
        /* [] */0
      ]
    ]);

var separator = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.height(/* Pt */Block.__(0, [1.0])),
      /* :: */[
        Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#ededed"])),
        /* :: */[
          Style$BsReactNative.marginTop(/* Pt */Block.__(0, [5.0])),
          /* :: */[
            Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [5.0])),
            /* [] */0
          ]
        ]
      ]
    ]);

var listItemContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.display(/* Flex */0),
      /* :: */[
        Style$BsReactNative.flexWrap(/* Nowrap */1),
        /* :: */[
          Style$BsReactNative.flexDirection(/* Row */0),
          /* [] */0
        ]
      ]
    ]);

var listIndex = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.125),
      /* :: */[
        Style$BsReactNative.alignSelf(/* Center */2),
        /* [] */0
      ]
    ]);

var listContent = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.740),
      /* :: */[
        Style$BsReactNative.paddingLeft(/* Pt */Block.__(0, [5.0])),
        /* :: */[
          Style$BsReactNative.paddingRight(/* Pt */Block.__(0, [5.0])),
          /* [] */0
        ]
      ]
    ]);

var title = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.paddingTop(/* Pt */Block.__(0, [5.0])),
      /* :: */[
        Style$BsReactNative.fontWeight(/* Bold */737455525),
        /* [] */0
      ]
    ]);

var domain = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontStyle(/* Italic */1),
      /* :: */[
        grayColor,
        /* [] */0
      ]
    ]);

var timeAgoAndUserAndLinkContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.display(/* Flex */0),
      /* :: */[
        Style$BsReactNative.flexDirection(/* Row */0),
        /* :: */[
          Style$BsReactNative.justifyContent(/* SpaceBetween */5),
          /* [] */0
        ]
      ]
    ]);

var timeAgoAndUser = Style$BsReactNative.style(/* :: */[
      grayColor,
      /* [] */0
    ]);

var commentAndShareContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.flex(0.135),
      /* :: */[
        Style$BsReactNative.display(/* Flex */0),
        /* :: */[
          Style$BsReactNative.flexDirection(/* Column */2),
          /* :: */[
            Style$BsReactNative.justifyContent(/* SpaceBetween */5),
            /* [] */0
          ]
        ]
      ]
    ]);

var commentContainer = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.display(/* Flex */0),
      /* :: */[
        Style$BsReactNative.flexDirection(/* Row */0),
        /* :: */[
          Style$BsReactNative.alignItems(/* Center */2),
          /* [] */0
        ]
      ]
    ]);

var linkImage = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginRight(/* Pt */Block.__(0, [5.0])),
      imageSize
    ]);

var shareImage = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginTop(/* Pt */Block.__(0, [12.0])),
      imageSize
    ]);

var commentCount = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.paddingLeft(/* Pt */Block.__(0, [3.0])),
      /* [] */0
    ]);

var NewsPage = /* module */[
  /* newsContainer */newsContainer,
  /* separator */separator,
  /* listItemContainer */listItemContainer,
  /* listIndex */listIndex,
  /* listContent */listContent,
  /* title */title,
  /* domain */domain,
  /* timeAgoAndUserAndLinkContainer */timeAgoAndUserAndLinkContainer,
  /* timeAgoAndUser */timeAgoAndUser,
  /* commentAndShareContainer */commentAndShareContainer,
  /* commentContainer */commentContainer,
  /* linkImage */linkImage,
  /* shareImage */shareImage,
  /* commentCount */commentCount
];

var container = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.display(/* Flex */0),
      /* :: */[
        hackerNewsContentBackgroundColor,
        /* [] */0
      ]
    ]);

function item(level) {
  var match = level === 0;
  var marginTopVal = match ? 1.0 : 2.5;
  var match$1 = level % 7;
  var borderColor;
  switch (match$1) {
    case -1 : 
        borderColor = "#F6F6EF";
        break;
    case 0 : 
        borderColor = "#e74c3c";
        break;
    case 1 : 
        borderColor = "#34ace0";
        break;
    case 2 : 
        borderColor = "#33d9b2";
        break;
    case 3 : 
        borderColor = "#ffda79";
        break;
    case 4 : 
        borderColor = "#ff793f";
        break;
    case 5 : 
        borderColor = "#ffb142";
        break;
    case 6 : 
        borderColor = "#40407a";
        break;
    default:
      borderColor = "#84817a";
  }
  return Style$BsReactNative.style(/* :: */[
              Style$BsReactNative.borderLeftColor(/* String */Block.__(0, [borderColor])),
              /* :: */[
                Style$BsReactNative.borderLeftWidth(3.0),
                /* :: */[
                  Style$BsReactNative.paddingLeft(/* Pt */Block.__(0, [5.0])),
                  /* :: */[
                    Style$BsReactNative.marginTop(/* Pt */Block.__(0, [marginTopVal])),
                    /* :: */[
                      hackerNewsContentBackgroundColor,
                      /* :: */[
                        Style$BsReactNative.elevation(2.0),
                        /* :: */[
                          Style$BsReactNative.shadowColor(/* String */Block.__(0, ["#000000"])),
                          /* :: */[
                            Style$BsReactNative.shadowOpacity(0.4),
                            /* :: */[
                              Style$BsReactNative.shadowRadius(1.0),
                              /* :: */[
                                Style$BsReactNative.shadowOffset(1.0, 0.0),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Comment = /* module */[
  /* container */container,
  /* item */item
];

var paddingLeft = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.paddingLeft(/* Pt */Block.__(0, [8.0])),
      /* [] */0
    ]);

var CommentsPage = /* module */[/* paddingLeft */paddingLeft];

exports.RefreshButton = RefreshButton;
exports.hackerNewsHeaderBackgroundColor = hackerNewsHeaderBackgroundColor;
exports.hackerNewsContentBackgroundColor = hackerNewsContentBackgroundColor;
exports.grayColor = grayColor;
exports.activityIndicator = activityIndicator;
exports.pageContainer = pageContainer;
exports.Common = Common;
exports.NewsPage = NewsPage;
exports.Comment = Comment;
exports.CommentsPage = CommentsPage;
/* floatingActionButton Not a pure module */
