// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var AppStyle = require("./AppStyle.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Image$BsReactNative = require("bs-react-native/src/components/image.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var TouchableOpacity$BsReactNative = require("bs-react-native/src/components/touchableOpacity.js");

var refreshImageSource_001 = require("../assets/refresh.png");

var refreshImageSource = /* `Required */[
  202657151,
  refreshImageSource_001
];

var fab = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#F7F5F8"])),
      /* :: */[
        Style$BsReactNative.borderStyle(/* Solid */0),
        /* :: */[
          Style$BsReactNative.borderColor(/* String */Block.__(0, ["black"])),
          /* :: */[
            Style$BsReactNative.width(/* Pt */Block.__(0, [40.0])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [40.0])),
              /* :: */[
                Style$BsReactNative.borderRadius(100.0),
                /* :: */[
                  Style$BsReactNative.position(/* Absolute */0),
                  /* :: */[
                    Style$BsReactNative.bottom(/* Pt */Block.__(0, [5.0])),
                    /* :: */[
                      Style$BsReactNative.right(/* Pt */Block.__(0, [20.0])),
                      /* :: */[
                        Style$BsReactNative.alignItems(/* Center */2),
                        /* :: */[
                          Style$BsReactNative.justifyContent(/* Center */2),
                          /* :: */[
                            Style$BsReactNative.elevation(2.0),
                            /* :: */[
                              Style$BsReactNative.shadowColor(/* String */Block.__(0, ["#000000"])),
                              /* :: */[
                                Style$BsReactNative.shadowOpacity(0.4),
                                /* :: */[
                                  Style$BsReactNative.shadowRadius(1.0),
                                  /* :: */[
                                    Style$BsReactNative.shadowOffset(1.0, 0.0),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Style = /* module */[/* fab */fab];

var component = ReasonReact.statelessComponent("BackToTopButton");

function make(onPress, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(fab), undefined, onPress, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, refreshImageSource, Js_primitive.some(AppStyle.image), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.refreshImageSource = refreshImageSource;
exports.Style = Style;
exports.component = component;
exports.make = make;
/* refreshImageSource Not a pure module */
