// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function news(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* points */Json_decode.optional((function (param) {
                  return Json_decode.field("points", Json_decode.$$int, param);
                }), json),
          /* user */Json_decode.optional((function (param) {
                  return Json_decode.field("user", Json_decode.string, param);
                }), json),
          /* time */Json_decode.field("time", Json_decode.$$int, json),
          /* time_ago */Json_decode.field("time_ago", Json_decode.string, json),
          /* comments_count */Json_decode.field("comments_count", Json_decode.$$int, json),
          /* type_ */Json_decode.field("type", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json),
          /* domain */Json_decode.optional((function (param) {
                  return Json_decode.field("domain", Json_decode.string, param);
                }), json)
        ];
}

function newsList(json) {
  return Json_decode.list(news, json);
}

function comment(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* level */Json_decode.field("level", Json_decode.$$int, json),
          /* user */Json_decode.optional((function (param) {
                  return Json_decode.field("user", Json_decode.string, param);
                }), json),
          /* time */Json_decode.field("time", Json_decode.$$int, json),
          /* time_ago */Json_decode.field("time_ago", Json_decode.string, json),
          /* content */Json_decode.field("content", Json_decode.string, json),
          /* comments */Json_decode.field("comments", (function (param) {
                  return Json_decode.list(comment, param);
                }), json)
        ];
}

function story(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* points */Json_decode.optional((function (param) {
                  return Json_decode.field("points", Json_decode.$$int, param);
                }), json),
          /* user */Json_decode.optional((function (param) {
                  return Json_decode.field("user", Json_decode.string, param);
                }), json),
          /* time */Json_decode.field("time", Json_decode.$$int, json),
          /* time_ago */Json_decode.field("time_ago", Json_decode.string, json),
          /* type_ */Json_decode.field("type", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json),
          /* domain */Json_decode.optional((function (param) {
                  return Json_decode.field("domain", Json_decode.string, param);
                }), json),
          /* comments */Json_decode.field("comments", (function (param) {
                  return Json_decode.list(comment, param);
                }), json)
        ];
}

var Decode = /* module */[
  /* news */news,
  /* newsList */newsList,
  /* comment */comment,
  /* story */story
];

var domain = "https://ikewat-hnapi.now.sh";

function fetchNewList($staropt$star, param) {
  var id = $staropt$star !== undefined ? $staropt$star : "1";
  return fetch(domain + ("/news?page=" + id)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Json_decode.list(news, json));
              }));
}

function fetchStory(id) {
  return fetch(domain + ("/item/" + id)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(story(json));
              }));
}

exports.Decode = Decode;
exports.domain = domain;
exports.fetchNewList = fetchNewList;
exports.fetchStory = fetchStory;
/* No side effect */
