// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactNative = require("react-native");
var ExpoWebBrowser = require("expo-web-browser");
var ReactNativeRenderHtml = require("react-native-render-html");

function onLinkPress(_evt, href) {
  ExpoWebBrowser.openBrowserAsync(href);
  return /* () */0;
}

var component = ReasonReact.statelessComponent("HtmlView");

function HtmlView(Props) {
  var content = Props.content;
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNativeRenderHtml.default, {
                    html: content,
                    textSelectable: true,
                    onLinkPress: onLinkPress
                  })
            });
}

var make = HtmlView;

exports.onLinkPress = onLinkPress;
exports.component = component;
exports.make = make;
/* component Not a pure module */
