// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactNativeRenderHtml = require("react-native-render-html");

function make(renderers, ignoredTags, ignoredStyles, allowedStyles, decodeEntities, debug, listsPrefixesRenderers, ignoreNodesFunction, alterData, alterChildren, alterNode, html, uri, tagsStyles, classesStyles, containerStyle, customWrapper, onLinkPress, onParsed, imagesMaxWidth, staticContentMaxWidth, imagesInitialDimensions, emSize, ptSize, baseFontStyle, textSelectable, renderersProps, allowFontScaling) {
  var partial_arg = {
    renderers: renderers,
    ignoredTags: ignoredTags,
    ignoredStyles: ignoredStyles,
    allowedStyles: allowedStyles,
    decodeEntities: decodeEntities,
    debug: debug,
    listsPrefixesRenderers: listsPrefixesRenderers,
    ignoreNodesFunction: ignoreNodesFunction,
    alterData: alterData,
    alterChildren: alterChildren,
    alterNode: alterNode,
    html: html,
    uri: uri,
    tagsStyles: tagsStyles,
    classesStyles: classesStyles,
    containerStyle: containerStyle,
    customWrapper: customWrapper,
    onLinkPress: onLinkPress,
    onParsed: onParsed,
    imagesMaxWidth: imagesMaxWidth,
    staticContentMaxWidth: staticContentMaxWidth,
    imagesInitialDimensions: imagesInitialDimensions,
    emSize: emSize,
    ptSize: ptSize,
    baseFontStyle: baseFontStyle,
    textSelectable: textSelectable,
    renderersProps: renderersProps,
    allowFontScaling: allowFontScaling
  };
  var partial_arg$1 = ReactNativeRenderHtml.default;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
