// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var NewsPage = require("./NewsPage.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CommentsPage = require("./CommentsPage.bs.js");
var StackNavigator$BsReactNavigation = require("bs-react-navigation/src/StackNavigator.bs.js");

function getScreen(route, navigation) {
  if (route) {
    return /* tuple */[
            ReasonReact.element(undefined, undefined, CommentsPage.make(route[1], /* array */[])),
            { }
          ];
  } else {
    return /* tuple */[
            ReasonReact.element(undefined, undefined, NewsPage.make(navigation, /* array */[])),
            {
              title: "News"
            }
          ];
  }
}

var Stack = StackNavigator$BsReactNavigation.Create(/* module */[
      /* initialRoute : News */0,
      /* getScreen */getScreen
    ]);

var render = Stack[/* render */11];

exports.Stack = Stack;
exports.render = render;
/* Stack Not a pure module */
