// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AppStyle = require("./AppStyle.bs.js");
var ReactCompat = require("reason-react-compat/src/ReactCompat.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactNative = require("react-native");

var refreshImageSource = require("../assets/refresh.png");

var component = ReasonReact.statelessComponent("RefreshButton");

function RefreshButton(Props) {
  var onPress = Props.onPress;
  return ReactCompat.useRecordApi(/* record */[
              /* debugName */component[/* debugName */0],
              /* reactClassInternal */component[/* reactClassInternal */1],
              /* handedOffState */component[/* handedOffState */2],
              /* willReceiveProps */component[/* willReceiveProps */3],
              /* didMount */component[/* didMount */4],
              /* didUpdate */component[/* didUpdate */5],
              /* willUnmount */component[/* willUnmount */6],
              /* willUpdate */component[/* willUpdate */7],
              /* shouldUpdate */component[/* shouldUpdate */8],
              /* render */(function (_self) {
                  return React.createElement(ReactNative.TouchableOpacity, {
                              style: AppStyle.RefreshButton[/* floatingActionButton */0],
                              onPress: onPress,
                              children: React.createElement(ReactNative.Image, {
                                    source: refreshImageSource,
                                    style: AppStyle.Common[/* image */6]
                                  })
                            });
                }),
              /* initialState */component[/* initialState */10],
              /* retainedProps */component[/* retainedProps */11],
              /* reducer */component[/* reducer */12],
              /* jsElementWrapped */component[/* jsElementWrapped */13]
            ]);
}

var make = RefreshButton;

exports.refreshImageSource = refreshImageSource;
exports.component = component;
exports.make = make;
/* refreshImageSource Not a pure module */
