// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AppStyle = require("./AppStyle.bs.js");
var NewsPage = require("./NewsPage.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var CommentsPage = require("./CommentsPage.bs.js");
var ReactNavigation = require("react-navigation");
var AppContainer$ReactNavigation = require("reason-react-navigation/src/AppContainer.bs.js");

var $$navigator = ReactNavigation.createStackNavigator({
      News: {
        screen: NewsPage.make,
        navigationOptions: (function (param) {
            return {
                    title: "Top News",
                    headerStyle: AppStyle.hackerNewsHeaderBackgroundColor
                  };
          })
      },
      Comments: {
        screen: CommentsPage.make,
        navigationOptions: (function (options) {
            var navigation = options.navigation;
            var title = Belt_Option.mapWithDefault(Caml_option.nullable_to_opt(navigation.getParam("title")), "Comments", (function (t) {
                    return t;
                  }));
            return {
                    title: title,
                    headerStyle: AppStyle.hackerNewsHeaderBackgroundColor
                  };
          })
      }
    });

var AppContainer = AppContainer$ReactNavigation.Make(/* module */[/* navigator */$$navigator]);

function StackNavigation(Props) {
  return React.createElement(AppContainer[/* make */0], { });
}

var make = StackNavigation;

exports.AppContainer = AppContainer;
exports.make = make;
/* AppContainer Not a pure module */
